version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    image: t4e1/grid-backend:latest
    container_name: app
    environment:
      SPRING_REDIS_HOST: redis
    ports:
      - "5000:8080"
    depends_on:
      - redis
