spring:
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/erp
    username: root
    password: root

application:
  security:
    jwt:
      secretKey: dGVhbTUtZmluYWwtcHJvamVjdC1ncmlkLUhSLWVycC1XZS1tYWtlcy1iZXR0ZXItZW50ZXJwcmlzZS1lbnZpcm9ubWVudAo=
      expiration_time: 300000 # 5분
      refresh-token:
        expiration_time: 86400000 # 하루